top_left: [40.06311850965281, 32.53801248525199]

bottom_right: [39.72127193759234, 33.064864778803724] 

# h = roads only
# m = standard roadmap
# p = terrain
# r = somehow altered roadmap
# s = satellite only
# t = terrain only
# y = hybrid

# indirilen harita turunu yukarıdaki harflere gore secebilirsiniz.

map_type: m